### ISSUE TITLE
505 error

### ISSUE THREAD

**Issue by vandan-r** [nicolewhite/neo4j-flask#1] opened 2015-03-05 05:06 UTC
i cloned the repo and used the same code. i got the neo4j server running on localhost/7474. But when i run the app i get a 505 error saying :Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. Please help me resolve it.
![505](https://cloud.githubusercontent.com/assets/5222803/6499557/784a4490-c323-11e4-9310-d43c7f68b217.png)

**Comment by nicolewhite** [comment] 2015-03-05 06:38
I am unable to reproduce your error. In `run.py`, can you change

```python
app.run(host='0.0.0.0', port=port)
```

to

```python
app.run(host='0.0.0.0', port=port, debug=True)
```

and tell me if you get a stacktrace when visiting localhost:5000 after restarting?

**Comment by vandan-r** [comment] 2015-03-05 07:50
i got a py2neo.error.unauthorised on the browser. this is the stacktrace.
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
127.0.0.1 - - [05/Mar/2015 13:17:06] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vandan/my-flask/projects/neo4j/neo4j-flask/blog/views.py", line 8, in index
    posts = get_todays_recent_posts()
  File "/home/vandan/my-flask/projects/neo4j/neo4j-flask/blog/models.py", line 137, in get_todays_recent_posts
    posts = graph.cypher.execute(query, today = date())
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/py2neo/core.py", line 677, in cypher
    metadata = self.resource.metadata
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/py2neo/core.py", line 228, in metadata
    self.get()
  File "/home/vandan/my-flask/projects/neo4j/neo4j-blog/lib/python2.7/site-packages/py2neo/core.py", line 276, in get
    raise Unauthorized(self.uri.string)
Unauthorized: http://localhost:7474/db/data/
127.0.0.1 - - [05/Mar/2015 13:17:07] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [05/Mar/2015 13:17:07] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Mar/2015 13:17:07] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Mar/2015 13:17:08] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [05/Mar/2015 13:17:08] "GET /?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
127.0.0.1 - - [05/Mar/2015 13:17:08] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

![stacktrace](https://cloud.githubusercontent.com/assets/5222803/6501123/639f1694-c33a-11e4-8533-edb1dd935a84.png)

**Comment by nicolewhite** [comment] 2015-03-07 20:43
Ah, you must be on Neo4j 2.2. You'll need to authenticate in `models.py` when connecting to the graph. http://py2neo.org/2.0/essentials.html#authentication

I'll close this issue once I make some changes to the code to reflect this.

**Comment by nicolewhite** [comment] 2015-04-03 22:45
Closing with https://github.com/nicolewhite/neo4j-flask/commit/5f26fc91d5879a09fc9108ecf2359c1806151fe6

**Closed by nicolewhite** 2015-04-03 22:45 UTC
